steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/swifora/dma-platform'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyC6xVrYGXETSr7xrrLstMzmg_JE0rhxsEM'
      - '.'

images:
  - 'gcr.io/swifora/dma-platform'
